export const ADD_ADMIN = 'ADD_ADMIN';  
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';  
export const DELETE_CUSTOMER='DELETE_CUSTOMER';
export const SEARCH_CUSTOMER='SEARCH_CUSTOMER';
export const RESET_CUSTOMER='RESET_CUSTOMER';
